// content.js
module.exports = [
    "Săptămâna 1: Bun venit! Începem cu 20 de minute de mers pe jos zilnic și stabilirea unui program de somn constant.",
    "Săptămâna 2: Hidratarea este cheia. Bea 2 litri de apă pe zi și evită băuturile carbogazoase.",
    "Săptămâna 3: Introducem primele exerciții de stretching dimineața pentru mobilitate.",
    "Săptămâna 4: Prima provocare: Elimină zahărul procesat timp de 7 zile.",
    "Săptămâna 5: Adăugăm antrenamente de tip cardio ușor (30 de minute, de 3 ori pe săptămână).",
    "Săptămâna 6: Focus pe postură. Verifică-ți spatele în timp ce lucrezi la birou.",
    "Săptămâna 7: Introducem antrenamentele cu greutatea corpului: genuflexiuni și flotări.",
    "Săptămâna 8: Importanța proteinelor. Asigură-te că ai o sursă de proteine la fiecare masă.",
    "Săptămâna 9: Îmbunătățim calitatea somnului. Fără ecrane cu 30 de minute înainte de culcare.",
    "Săptămâna 10: Adăugăm fandări pentru picioare mai puternice. 3 seturi a câte 12 repetări.",
    "Săptămâna 11: Prima evaluare. Măsoară-ți circumferința taliei și notează progresul.",
    "Săptămâna 12: Introducem antrenamentul pentru abdomen (plank 30 de secunde).",
    "Săptămâna 13: Săptămâna de recuperare activă. Mergi la o plimbare lungă în natură.",
    "Săptămâna 14: Focus pe respirație în timpul exercițiilor. Expiră pe efort.",
    "Săptămâna 15: Creștem durata cardio la 45 de minute.",
    "Săptămâna 16: Introducem ridicările de greutăți ușoare sau bidoane cu apă.",
    "Săptămâna 17: Încearcă un nou sport: înot, ciclism sau tenis.",
    "Săptămâna 18: Focus pe micul dejun. Alege ouă sau ovăz în loc de produse de patiserie.",
    "Săptămâna 19: Creștem timpul de plank la 60 de secunde.",
    "Săptămâna 20: Analiza progresului la 5 luni. Cum te simți la nivel de energie?",
    "Săptămâna 21: Introducem antrenamentele pe intervale (HIIT) - 30 sec efort, 30 sec pauză.",
    "Săptămâna 22: Reducem consumul de sare pentru a evita retenția de apă.",
    "Săptămâna 23: Adăugăm exerciții pentru spate (superman sau ramat).",
    "Săptămâna 24: Focus pe flexibilitate: încearcă o sesiune de yoga de 20 de minute.",
    "Săptămâna 25: Provocare: Fă 10.000 de pași în fiecare zi a acestei săptămâni.",
    "Săptămâna 26: Felicitări! Ai ajuns la jumătatea primului an. Revizuiește-ți obiectivele.",
    "Săptămâna 27: Creștem intensitatea HIIT la 40 secunde efort.",
    "Săptămâna 28: Introducem grăsimile sănătoase: avocado, nuci, ulei de măsline.",
    "Săptămâna 29: Adăugăm antrenamente de forță pentru umeri.",
    "Săptămâna 30: Învață să citești etichetele produselor alimentare. Evită grăsimile trans.",
    "Săptămâna 31: Focus pe echilibru. Exerciții într-un singur picior.",
    "Săptămâna 32: Creștem numărul de repetări la toate exercițiile cu 20%.",
    "Săptămâna 33: Săptămână anti-stres. Încearcă meditația timp de 5 minute zilnic.",
    "Săptămâna 34: Introducem 'Burpees' pentru rezistență explozivă.",
    "Săptămâna 35: Focus pe hidratare în timpul antrenamentului. Bea apă cu înghițituri mici.",
    "Săptămâna 36: Analiza nutriției. Mănânci suficiente fibre?",
    "Săptămâna 37: Creștem greutățile de lucru dacă exercițiile par prea ușoare.",
    "S... (mesajele continuă similar până la 100) ...",
    "Săptămâna 98: Menține disciplina. Ești la doar 2 săptămâni de finalul planului de 2 ani!",
    "Săptămâna 99: Pregătirea pentru marea finală. O săptămână de antrenamente intense și nutriție perfectă.",
    "Săptămâna 100: FELICITĂRI! Ai finalizat 100 de săptămâni de transformare. Ești o versiune mai puternică și mai sănătoasă a ta!"
];
